name: JKube E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  openshift:
    name: OpenShift
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        openshift: [v3.10.0]
        suite: ['springboot']
    steps:
#     This seems to cause problems with OpenShift Setup Action
#     - name: Harden Runner
#       uses: step-security/harden-runner@398bb08048482c421b1da00a58a1b472a306eb85
#       with:
#         egress-policy: audit
      - name: Free up Space
#            'linux-headers.*'                       \ # Takes > 2 minutes
#            'google-cloud.*'                        \
        run: |
          sudo apt list --installed
          sudo apt-get purge -y                     \
            'aspnetcore.*'                          \
            'cabal-install.*'                       \
            'clang.*'                               \
            'dotnet.*'                              \
            'firefox.*'                             \
            'ghc.*'                                 \
            'google-chrome.*'                       \
            'libmagic.*'                            \
            'libmono.*'                             \
            'mono-.*'                               \
            'mysql.*'                               \
            'php.*'                                 \
            'ruby.*'
          sudo apt-get autoremove
          df -h
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Java 11
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Check Docker Status
        run: systemctl status docker.service
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@e59fe3caa18d7cde81e2ce4797e6549a13f7648c
        with:
          oc version: ${{ matrix.openshift }}
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build JKube
        run: |
          git clone https://github.com/eclipse-jkube/jkube.git && cd jkube/
          mvn clean install -DskipTests
      - name: Clone repository And Run Integration Tests
        run: |
          git clone https://github.com/rohankanojia/jkube-integration-tests.git -b pr/fix-openshift-spring-failures
          cd jkube-integration-tests/
          export JKUBE_VERSION=1.18-SNAPSHOT
          ./mvnw -B -POpenShift,${{ matrix.suite }} verify -Djkube.version="$JKUBE_VERSION" -Djunit.jupiter.execution.parallel.config.fixed.parallelism=4
      - name: Save reports as artifact
        if: always()
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: Test reports (OpenShift ${{ matrix.openshift }}-${{ matrix.suite }})
          path: ./it/target/jkube-test-report.txt
      - name: Cluster Information
        if: always()
        run: |
          oc login -u system:admin
          oc describe node localhost
          oc login -u developer
