name: E2E Tests OKD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Run OKD bundle with crc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.22'
    env:
      SHELL: /bin/bash
      KUBECONFIG: '/Users/runner/.kube/config'
      CRC_VERSION: 2.41.0
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Install required virtualization software
        run: |
          sudo apt-get update
          sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system
          sudo usermod -a -G libvirt $USER
      - name: Remove unwanted stuff to free up disk image
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          sudo docker image prune --all --force

          sudo swapoff -a
          sudo rm -f /mnt/swapfile
          sudo adduser $USER libvirt
          sudo adduser $USER kvm
          sudo usermod -a -G libvirt $USER
      - name: Download CRC
        run: |
          wget https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/${CRC_VERSION}/crc-linux-amd64.tar.xz
          tar -xJf crc-linux-amd64.tar.xz
          sudo cp crc-linux-${CRC_VERSION}-amd64/crc /usr/local/bin/crc
      - name: Set the crc config
        run: |
          crc config set preset okd
          crc config set network-mode user
      - name: Setup the crc
        run: |
          sudo -su $USER crc setup
      - name: Start the crc
        run: sudo -su $USER crc start
      - name: Login into OpenShift Cluster
        run: |
          sudo -su $USER eval $(crc oc-env)         
          sudo -su $USER oc version
          LOGIN_COMMAND=`sudo -su $USER crc console --credentials | grep admin | awk -F"'" '$0=$2'`
          eval $LOGIN_COMMAND
          sudo -su $USER oc api-resources
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Eclipse JKube Test
        run: |
          git clone https://github.com/rohanKanojia/eclipse-jkube-demo-project.git
          cd eclipse-jkube-demo-project
          sudo -su $USER mvn package oc:build oc:resource oc:apply  
