name: MacOS E2E CRC OKD Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # Every day at 4am

env:
  IT_REVISION: master
  IT_MODULE: kubernetes-itests
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
  SHELL: /bin/bash

jobs:
  openshift-kubernetes-distribution:
    name: CRC ${{ matrix.crc }} / OKD ${{ matrix.okd }}
    runs-on: macos-13
#    if: github.repository == 'fabric8io/kubernetes-client'
    strategy:
      fail-fast: false
      matrix:
        # There is some problem with latest version of crc configured with okd preset. I
        # wasn't able to run tests successfully on latest version of crc. See linked issue:
        # https://github.com/crc-org/crc/issues/4382
        # TODO: Update CRC version to latest when aforementioned issue gets resolved
        okd: [ v4.14.0 ]
        crc: [ 2.32.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install required virtualization software
        run: |
          #sudo apt-get update
          #sudo apt install --ignore-missing qemu-kvm libvirt-daemon libvirt-daemon-system virtiofsd
          #sudo adduser $USER libvirt
          #sudo adduser $USER kvm
          #sudo usermod -a -G libvirt $USER
      - name: Remove unwanted stuff to free up disk image
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          sudo docker image prune --all --force

          sudo swapoff -a
          sudo rm -f /mnt/swapfile
      - name: Download CRC
        run: |
          wget https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/${{ matrix.crc }}/crc-linux-amd64.tar.xz
          tar -xJf crc-linux-amd64.tar.xz
          sudo cp crc-linux-${{ matrix.crc }}-amd64/crc /usr/local/bin/crc
      - name: Set the crc config
        run: |

          crc config set preset okd
          crc config set network-mode user
      - name: Setup the crc
        run: |
          sudo -su $USER crc setup
      - name: Start the crc
        run: sudo -su $USER crc start
      - name: Login into OpenShift Cluster
        run: |
          sudo -su $USER eval $(crc oc-env)
          sudo -su $USER oc version
          LOGIN_COMMAND=`sudo -su $USER crc console --credentials | grep admin | awk -F"'" '$0=$2'`
          eval $LOGIN_COMMAND
      - name: Run Fabric8 Kubernetes Client Tests
        run: |
          git clone https://github.com/rohanKanojia/kubernetes-client -b pr/okd-crc-ci-pipeline
          cd kubernetes-client
          mvn clean install -DskipTests 
          cd kubernetes-itests/
          sudo -su $USER mvn clean install -Dtest="io.fabric8.openshift.**"
